version: '3.1'
services:
  mysql-db-container:
    container_name: mysql-db-container
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=CryptoWalletRootPassword
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d