version: '2.2'
services:
  mysql-db-container:
    container_name: mysql-db-container
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=CryptoWalletRootPassword
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  cryptowallet-backend-container:
    container_name: cryptowallet-backend-container
    depends_on:
      - mysql-db-container
    image: delormeloic26/cryptowallet-backend:latest
    links:
      - mysql-db-container
    restart: always
    environment:
      - VIRTUAL_PORT=8090
      - VIRTUAL_HOST=cryptowallet.loic-delorme.fr
      - HTTPS_METHOD=noredirect
      - LETSENCRYPT_HOST=cryptowallet.loic-delorme.fr
      - LETSENCRYPT_EMAIL=loic.delorme.pro@gmail.com

  nginx-proxy-container:
    container_name: nginx-proxy-container
    depends_on:
      - cryptowallet-backend-container
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-companion-container:
    container_name: nginx-proxy-companion-container
    depends_on:
      - cryptowallet-backend-container
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - ./config/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy-container